test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------
      exclude = ["install.private", "install.nourl", "install.multi"]
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.89f4f52.name = "Upgrade from 13.0.5"
