test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------
      exclude = ["install.nourl"]
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

   
